python ../glance_dir.py --db barebones_nexp2_v1.6_10yrs.db
python ../glance_dir.py --db barebones_v1.6_10yrs.db
python ../glance_dir.py --db baseline_nexp1_v1.6_10yrs.db
python ../glance_dir.py --db baseline_nexp2_scaleddown_v1.6_10yrs.db
python ../glance_dir.py --db baseline_nexp2_v1.6_10yrs.db
python ../glance_dir.py --db combo_dust_nexp2_v1.6_10yrs.db
python ../glance_dir.py --db combo_dust_v1.6_10yrs.db
python ../glance_dir.py --db ddf_heavy_nexp2_v1.6_10yrs.db
python ../glance_dir.py --db ddf_heavy_v1.6_10yrs.db
python ../glance_dir.py --db dm_heavy_nexp2_v1.6_10yrs.db
python ../glance_dir.py --db dm_heavy_v1.6_10yrs.db
python ../glance_dir.py --db even_filters_alt_g_v1.6_10yrs.db
python ../glance_dir.py --db even_filters_altv1.6_10yrs.db
python ../glance_dir.py --db even_filters_g_v1.6_10yrs.db
python ../glance_dir.py --db even_filtersv1.6_10yrs.db
python ../glance_dir.py --db mw_heavy_nexp2_v1.6_10yrs.db
python ../glance_dir.py --db mw_heavy_v1.6_10yrs.db
python ../glance_dir.py --db rolling_exgal_mod2_dust_sdf_0.80_nexp2_v1.6_10yrs.db
python ../glance_dir.py --db rolling_exgal_mod2_dust_sdf_0.80_v1.6_10yrs.db
python ../glance_dir.py --db rolling_fpo_2nslice0.8_v1.6_10yrs.db
python ../glance_dir.py --db rolling_fpo_2nslice0.9_v1.6_10yrs.db
python ../glance_dir.py --db rolling_fpo_2nslice1.0_v1.6_10yrs.db
python ../glance_dir.py --db rolling_fpo_3nslice0.8_v1.6_10yrs.db
python ../glance_dir.py --db rolling_fpo_3nslice0.9_v1.6_10yrs.db
python ../glance_dir.py --db rolling_fpo_3nslice1.0_v1.6_10yrs.db
python ../glance_dir.py --db rolling_fpo_6nslice0.8_v1.6_10yrs.db
python ../glance_dir.py --db rolling_fpo_6nslice0.9_v1.6_10yrs.db
python ../glance_dir.py --db rolling_fpo_6nslice1.0_v1.6_10yrs.db
python ../glance_dir.py --db ss_heavy_nexp2_v1.6_10yrs.db
python ../glance_dir.py --db ss_heavy_v1.6_10yrs.db
python ../scimaf_dir.py --db barebones_nexp2_v1.6_10yrs.db
python ../scimaf_dir.py --db barebones_v1.6_10yrs.db
python ../scimaf_dir.py --db baseline_nexp1_v1.6_10yrs.db
python ../scimaf_dir.py --db baseline_nexp2_scaleddown_v1.6_10yrs.db
python ../scimaf_dir.py --db baseline_nexp2_v1.6_10yrs.db
python ../scimaf_dir.py --db combo_dust_nexp2_v1.6_10yrs.db
python ../scimaf_dir.py --db combo_dust_v1.6_10yrs.db
python ../scimaf_dir.py --db ddf_heavy_nexp2_v1.6_10yrs.db
python ../scimaf_dir.py --db ddf_heavy_v1.6_10yrs.db
python ../scimaf_dir.py --db dm_heavy_nexp2_v1.6_10yrs.db
python ../scimaf_dir.py --db dm_heavy_v1.6_10yrs.db
python ../scimaf_dir.py --db even_filters_alt_g_v1.6_10yrs.db
python ../scimaf_dir.py --db even_filters_altv1.6_10yrs.db
python ../scimaf_dir.py --db even_filters_g_v1.6_10yrs.db
python ../scimaf_dir.py --db even_filtersv1.6_10yrs.db
python ../scimaf_dir.py --db mw_heavy_nexp2_v1.6_10yrs.db
python ../scimaf_dir.py --db mw_heavy_v1.6_10yrs.db
python ../scimaf_dir.py --db rolling_exgal_mod2_dust_sdf_0.80_nexp2_v1.6_10yrs.db
python ../scimaf_dir.py --db rolling_exgal_mod2_dust_sdf_0.80_v1.6_10yrs.db
python ../scimaf_dir.py --db rolling_fpo_2nslice0.8_v1.6_10yrs.db
python ../scimaf_dir.py --db rolling_fpo_2nslice0.9_v1.6_10yrs.db
python ../scimaf_dir.py --db rolling_fpo_2nslice1.0_v1.6_10yrs.db
python ../scimaf_dir.py --db rolling_fpo_3nslice0.8_v1.6_10yrs.db
python ../scimaf_dir.py --db rolling_fpo_3nslice0.9_v1.6_10yrs.db
python ../scimaf_dir.py --db rolling_fpo_3nslice1.0_v1.6_10yrs.db
python ../scimaf_dir.py --db rolling_fpo_6nslice0.8_v1.6_10yrs.db
python ../scimaf_dir.py --db rolling_fpo_6nslice0.9_v1.6_10yrs.db
python ../scimaf_dir.py --db rolling_fpo_6nslice1.0_v1.6_10yrs.db
python ../scimaf_dir.py --db ss_heavy_nexp2_v1.6_10yrs.db
python ../scimaf_dir.py --db ss_heavy_v1.6_10yrs.db